---

- include: initial_check.yml

- include: download.yml
  tags:
    - download

- include: dependencies.yml
  tags:
    - install

- include: install.yml
  tags:
    - install

- include: redis_config.yml
  tags:
    - config
