---

- include: initial_check.yml

- include: download.yml
  tags:
    - download

- include: dependencies.yml
  tags:
    - install

- include: install.yml
  tags:
    - install

- include: redis_config.yml
  tags:
    - config

- include: redis_cluster.yml
  tags:
    - cluster
  when:
    - redis_cluster_enabled == "yes"
